### ISSUE TITLE
Translations of changed skills' descriptions

### ISSUE THREAD

**Issue by Warzyw647** [vcmi-mods/horn-of-the-abyss#101]
I see that the descriptions of SoD skills changed in in HotA do not have translations.
I'm talking about the descriptions that say what the Basic/Advanced/Expert skills do, visible in the hero screen after clicking those skills.

**Comment by GeorgeK1ng** [comment]
Game balance mod - translation for skills descriptions goes to separate translation file. Chinese, Czech and Ukrainian are already there.
**My Games\vcmi\Mods\hota\Mods\gameBalance\content\translation**

**Comment by IvanSavenko** [comment]
Closing. Support added in vcmi 1.6
