### ISSUE TITLE
Update new map to the latest and fix the Grotto in Cove

### ISSUE THREAD

**Issue by lishaoxia1985** [vcmi-mods/horn-of-the-abyss#111]

**Comment by Laserlicht** [comment]
Grotto related discussion: https://github.com/vcmi/vcmi/pull/4061

**Comment by lishaoxia1985** [comment]
@Laserlicht Sometimes when you use cheat code "vcmiartifacts" and put all Equipped weapons to Grotto the game will crash.

**Comment by Laserlicht** [comment]
@SoundSSGood Any idea for the problem?

**Comment by lishaoxia1985** [comment]
@Laserlicht Crashing occurs when Xbrz is enabled.
But using cheat code and putting all equiped artifacts on Grotto make no effect when xbrz is disabled.
![XueR.jpg](https://github.com/user-attachments/assets/62326ae5-1aba-4909-8d8e-50eb44eb5150)
