### ISSUE TITLE
Missing Spell Resarch Mechanism

### ISSUE THREAD

**Issue by Napkutya** [vcmi-mods/horn-of-the-abyss#122]
Spell research mechanic has been introduced, allowing for replacement of spells in your Mage Guild at a cost.
The Current version does not contain this :(

See the detailed description:
https://heroes3wog.net/spell-research-mechanic-horn-of-the-abyss/

**Comment by Olegmods** [comment]
It hasn't been implemented for now, but some VCMI devs are interested in this function.

**Comment by Napkutya** [comment]
It is a very desired functionality for many of us.
Fingers crossed :)
Thank You
