### ISSUE TITLE
Update to WOG Commander portraits (that nobody asked for)

### ISSUE THREAD

**Issue by Aph-ra** [vcmi-mods/horn-of-the-abyss#126]
Incredibly low priority but I thought why not? I managed to recreate the Cove background as pixel perfect as it's going to get so I might as well use it here. 2 versions - one using the creature def and one using the original closer-up pose (I wish people credited the origins of these defs, it'd help making portraits so much).

[Updating Cove WOG Commander.zip](https://github.com/user-attachments/files/17198561/Updating.Cove.WOG.Commander.zip)

**Comment by Olegmods** [comment]
AcidCave creature bank claims that the author is unknown. Also may I ask for Cove background. I added an alternative creature for the town, but without proper background.
