### ISSUE TITLE
Update to 1.7.50 

### ISSUE THREAD

**Issue by by003** [vcmi-mods/horn-of-the-abyss#177]
https://drive.google.com/file/d/1o4JLemKJEHJh0plU_BLx_zbWSVx6f1fp/view?usp=sharing

Please check.
Updates:
1. All campaign heroes are available.
2. Fix some ability in Factory, need the vcmi-extra mod.
3. New buttons for spell research.
4. Add many of map decorations from HotA 1.7
5. Fix Ring of Oblivion, added Sleepkeeper.
6. Supplementary mod by me. Including: Steel Golem Factory, Lightning Generator, Guard Tower, Wind Turbines and Kangaroos.
7. New artifacts from Supplementary mod, which is `Great Woe of the Crawlers` from the campaign plot of Forged in Fire.

**Comment by Olegmods** [comment]
My suggestions:

> 1. All campaign heroes are available.

Make HotA campaign heroes special and make them not special in HotA Campaign Heroes on map. Both for Factory ones and the other ones.

> 5. Fix Ring of Oblivion, added Sleepkeeper.

Maybe remove "**PARTIALLY IMPLEMENTED in VCMI**" part from the Ring of Oblivion if it works?

> 6. Supplementary mod by me. Including: Steel Golem Factory, Lightning Generator, Guard Tower, Wind Turbines and Kangaroos.
> 7. New artifacts from Supplementary mod, which is Great Woe of the Crawlers from the campaign plot of Forged in Fire.

Maybe supplementary mod should be disabled by default? I think some people will be confused if they see stuff not from HotA (but related to HotA) in the port of HotA.

**Comment by misiokles** [comment]
I'll into them later. Now testing time.
