### ISSUE TITLE
All / most of water objects should use "blockVisit" mode

### ISSUE THREAD

**Issue by krs0** [vcmi-mods/horn-of-the-abyss#42]
@IvanSavenko can you please detail a little what this is about?

**Comment by IvanSavenko** [comment]
In H3 most of buildings on land are visited when hero stands on top of them. E.g. hero needs to physically enter town/mine/dwelling to interact with it.

However, buildings on water are usually visited from tile next to the entrance - e.g. when you visit Mermaids your boat is not on top of Mermaids, but next to them.

In vcmi this is controlled by "blockVisit" / "blockedVisitable" property. If set to true, object will be visited when hero stands next to visited objects. And currently large number of new water objects from hota don't use such property.

**Comment by DjWarmonger** [comment]
Please wait for a proper solution of https://github.com/vcmi/vcmi/issues/847

**Comment by misiokles** [comment]
This Issue can be closed?

**Comment by DjWarmonger** [comment]
Right!
