### ISSUE TITLE
Create submod for OH3 sunds replaced by HotA

### ISSUE THREAD

**Issue by krs0** [vcmi-mods/horn-of-the-abyss#44]
Cove mod currently has several sounds that are replacing h3 sounds. Should be probably moved to another submod (check if not fixed already)

**Comment by IvanSavenko** [comment]
Don't think we need *new* submod for them, moving it to graphical fixes (potentially renaming it) is good enough IMO. Can't think of any use-case where players will want one but not another

**Comment by krs0** [comment]
These files are different:
From Armageddon's Blade, but does not matter in the end cause SoD has these as well.
![image](https://github.com/vcmi-mods/horn-of-the-abyss/assets/15194321/c2cb32ad-b4d9-46de-b060-e71c6afb3371)

From SoD
![image](https://github.com/vcmi-mods/horn-of-the-abyss/assets/15194321/3e80f23a-6dd0-47c8-b4d9-2b43f51df6e0)

**Comment by krs0** [comment]
Moved all sounds to graphicalFixes Mod.
Campaign sounds that are repurposed seem weird to me. Anyone has an idea why they differ?
```
ABvodb1.wav and same
g1a.wav and same
n1a.wav
S1A.wav and same
```

**Comment by IvanSavenko** [comment]
> Campaign sounds that are repurposed seem weird to me. Anyone has an idea why they differ?

They *might* have reused them for hota campaigns voiceover.

Hota campaign maps are not new maps but restyled h3 maps. Same is possibly true for their opening movies and voiceover (if they have it).

Another option is that this is simply unused content and can be removed. I've seen some such content in hota.lod
