### ISSUE TITLE
Incorrect mechanics for Sea Dog ability

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi-mods/horn-of-the-abyss#56]
Sea Dog should reuse DEATH_STARE ability from Might Gorgons, with the following properties:

- [ ] 3% to kill enemy creature in ranged attack without penatly
- [ ] 2% with range penalty
- [ ] No effect in melee

Modifying ability depending on range is not supported, but at least the basic formula of DEATH_STARE is balanced and gives expected numbers.

- [ ] Custom animation

**Comment by Warzyw647** [comment]
Pay attention to immunities. Nothing is immune to Pirate's shot, while some creatures are immune to Gorgon's Death Stare.
