### ISSUE TITLE
There is no such handler as "shrine"

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi-mods/horn-of-the-abyss#68]
This causes crash:
https://github.com/vcmi-mods/horn-of-the-abyss/commit/c2d7ccc782ef2beccd00036189ece16edb686ae8#diff-6894399578a1d17186d40dd3e70f3167c0619192b55795b7c1586a216169606e

The Shrine is now handled via "configurable", as in default config here: https://github.com/vcmi/vcmi/blob/develop/config/objects/shrine.json

**Comment by krs0** [comment]
diff is prior to configurable changes, so the crash is not from diff?

will look how to fix it though.

**Comment by krs0** [comment]
Should be fixed by: https://github.com/vcmi-mods/horn-of-the-abyss/pull/70

**Comment by misiokles** [comment]
This Issue can be closed?

**Comment by krs0** [comment]
Yup
