### ISSUE TITLE
HoTA mod crashed because of incorrect "Torosar " identifier

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi-mods/horn-of-the-abyss#69]
`[2023-Oct-25 10:01:58.493480] ERROR mod - Failed to resolve identifier torosar  of type hero from mod core`
Not sure where Torosar is referenced, but disabling HoTA mod fixes the issue.

[VCMI_Client_log.txt](https://github.com/vcmi-mods/horn-of-the-abyss/files/13162976/VCMI_Client_log.txt)

**Comment by krs0** [comment]
Is caused by my change to remove space after name.
Could not see crash because I have a prior crash I think related to string ID's
Should be fixed by: https://github.com/vcmi-mods/horn-of-the-abyss/pull/67

**Comment by DjWarmonger** [comment]
Confirmed, fresh mod works fine,
