### ISSUE TITLE
HotA maps are not supported in game

### ISSUE THREAD

**Issue by by003** [vcmi-mods/horn-of-the-abyss#75]
![image](https://github.com/vcmi-mods/horn-of-the-abyss/assets/127420617/97653b16-86f0-4620-9e46-462140805c3e)
It seems shrines cannot be read.

**Comment by by003** [comment]
@misiokles I cannot use HotA maps by using the latest update. Can you use these maps from the game? I am pretty sure all subtypes have been changed to strings. The current problem is shrines cannot be read in the game and crashed after these red sentences emerged.

**Comment by misiokles** [comment]
I don't know, I'm still sticking to stable 1.3.2 version. Please, create a issue at main github.

**Comment by by003** [comment]
I have already created the issue in the main github, I just wanna know whether it can run in latest build or not, in 1.3.2, subtypes were still be digit numbers but in 1.4.0 it must be changed into strings. Thus I have to test it in 1.4.0 build, but however 1.3.2 is really good for use.
