### ISSUE TITLE
Haspid's revenge ability

### ISSUE THREAD

**Issue by by003** [vcmi-mods/horn-of-the-abyss#79]
@misiokles  

Really need to add a sentence: "propagator" : "BATTLE_WIDE"
It is invalid if there is not this sentence.

![image](https://github.com/vcmi-mods/horn-of-the-abyss/assets/127420617/1a1a64eb-ddab-48ef-a3be-a521b5469a2c)

It have been tested and seems available.

**Comment by by003** [comment]
If finished please close this issue.

**Comment by by003** [comment]
@misiokles 
Please delete "addInfo": [0,2], or change it as "addInfo": 0
Now only melee attack will trigger the revenge ability, actually any attacks do.

**Comment by misiokles** [comment]
Ok, but...Haspids can make ranged attack?

**Comment by by003** [comment]
> Ok, but...Haspids can make ranged attack?

Of course it they cannot, however, they can be hurted by ranged attack. Thus, we need to make this condition valid to trigger.

**Comment by misiokles** [comment]
Done! But I must admit, I understand this bonus diffirent :)
