### ISSUE TITLE
Too small mask for Watering Place

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi-mods/horn-of-the-abyss#82]
<img width="104" alt="image" src="https://github.com/vcmi-mods/horn-of-the-abyss/assets/2566990/09987d03-cfcb-4d77-bb0f-3588007d3541">

Check this image for reference: https://heroes.thelazy.net/images/e/ed/Watering_Place_%28vs%29.png

**Comment by misiokles** [comment]
Fixed in 1.6.29 version
