### ISSUE TITLE
Plan for factory town and HotA 1.7 mods

### ISSUE THREAD

**Issue by by003** [vcmi-mods/horn-of-the-abyss#83]
I cannot create a pull request now, thus I use issues to create this.

It is easy to finish some parts in VCMI with factory town in HotA 1.7, which include some fundamental aspects, creatures, heroes, town and dwellings. 
In town buildings:
![image](https://github.com/vcmi-mods/horn-of-the-abyss/assets/127420617/011f5248-5682-4e0f-8b88-e10931fc6d41)
I haven't tested if limiter for days can be use in town buildings, maybe it is not available now.
![image](https://github.com/vcmi-mods/horn-of-the-abyss/assets/127420617/f7101fb9-bfc0-4b4e-94ed-8fda13519294)
Is open battle spell can be used as a lightning bolt?

For creature part:
![image](https://github.com/vcmi-mods/horn-of-the-abyss/assets/127420617/68814780-4f15-4e17-9e73-de8c5be363d1)
Detonation might not be available now, because we have no bonus type for a death trigger.
![image](https://github.com/vcmi-mods/horn-of-the-abyss/assets/127420617/068122b6-ff01-4835-8b18-5eba7eb28b5e)
For additional strike, it is easy to make an ability to accumulate additional strike, maybe using the same mechanic as Haspids. However, it is impossible for devouring corpses as a trigger.
![image](https://github.com/vcmi-mods/horn-of-the-abyss/assets/127420617/cdbcbcc8-78ea-40da-8498-2ac1561400a6)
Easy to finish the counterstrike for ranged attack, but I don't know if unlimitated retaliation can be used in ranged attack,as well as first strike.
![image](https://github.com/vcmi-mods/horn-of-the-abyss/assets/127420617/4e5f47ca-e293-4209-b9fa-51f20c699f53)
I used to make it available in a spell effect. But now damages can only reduced by 99%. Creatures can cast themselves now as well.
![image](https://github.com/vcmi-mods/horn-of-the-abyss/assets/127420617/824dcb6e-3c61-402f-a772-e1732c34f890)
Similar as red dragon in HoMM5. Now we cannot finish this, maybe do it as widely breath.

Sleepkeeper will be easy to finish.
![image](https://github.com/vcmi-mods/horn-of-the-abyss/assets/127420617/4b7c6a83-8b66-46bb-bdee-af3bad1fc50f)

I don't reckon random map editor can make beautiful walls. Just ban it in random map.
![image](https://github.com/vcmi-mods/horn-of-the-abyss/assets/127420617/6850c923-02fe-4365-85af-17e213c9ca76)

No way can realize airship now.
![image](https://github.com/vcmi-mods/horn-of-the-abyss/assets/127420617/c30a1cda-af6e-48fc-9630-e164a0cae69a)

**Comment by by003** [comment]
All coordinate values for factory town screen.
Village hall 0 264 0
Town Hall 0 256
City Hall 0 225
Capitol 0 163
Fort 369 63
Citadel 366 17
Castle 366 17
Tavern 680 230
Blacksmith 347 189
Mage Guild 1 132 235 -1
Mage Guild 2 132 211
Mage Guild 3 132 189
Mage Guild 4 132 166
Mage Guild 5 132 117
Marketplace 316 310
Resource Silo 227 347
Artifact Merchant 270 272
special 1 Bank 0 301 1
special 2 tower 117 9
Holy Grail 580 0
Dwelling 1 670 139
Dwelling 2 252 0 
Dwelling 3 187 174 up 187 95 horde 187 162
Dwelling 4 516 211
Dwelling 5 662 239
Dwelling 6 714 55 up 714 5
Dwelling 7-1 0 71 up 0 51
Dwelling 7-2 427 181 up 427 162
Decoration EX1 Bridge 245 201
Decoration EX2 House 499 295
Decoration EX3 Road 429 217

The def files for dwelling 2 cannot be opened by using def previewer, I cannot open them to convert into images. Z coordinates need to be adjusted while finish the town screen.

The coordinates for seige screen displays here.
"siege" : {
				"shooter" : "hotaGunman",
				"imagePrefix" : "factory/siege/SGFa",
				"towerIconSmall" : "factory/icons/towerSmall",
				"towerIconLarge" : "factory/icons/towerLarge",
				"gate" :
				{
					"arch" : { "x" : 481, "y" : 212 },
					"gate" : { "x" : 427, "y" : 281 }
				},
				"moat" :
				{
					"bank" : { "x" : 415, "y" : 80 },
					"moat" : { "x" : 415, "y" : 80 }
				},
				"static" :
				{
					"background" : { "x" : 631, "y" : 56 },
					"bottom" : { "x" : 530, "y" : 368 },
					"top" : { "x" : 511, "y" : 88 }
				},
				"towers" :
				{
					"bottom" :
					{
						"battlement" : { "x" : 613, "y" : 508 },
						"creature" : { "x" : 391, "y" : 311 },
						"tower" : { "x" : 613, "y" : 508 }
					},
					"keep" :
					{
						"battlement" : { "x" : 715, "y" : 156 },
						"creature" : { "x" : 536, "y" : -26 },
						"tower" : { "x" : 715, "y" : 156 }
					},
					"top" :
					{
						"battlement" : { "x" : 584, "y" : 14 },
						"creature" : { "x" : 356, "y" : -171 },
						"tower" : { "x" : 584, "y" : 14 }
					}
				},
				"walls" :
				{
					"bottom" : { "x" : 580, "y" : 459 },
					"bottomMid" : { "x" : 507, "y" : 318 },
					"upper" : { "x" : 557, "y" : 65 },
					"upperMid" : { "x" : 496, "y" : 185 }
				}
			},

**Comment by by003** [comment]
Some creatures need to be reworked, such as sandworm, if need a teleport moving.
Couatl's def file cannot be opened by def previewer, but fortunately, I have done a def model for couatl and crimson couatl before, by completed gif files.

**Comment by DjWarmonger** [comment]
For Sandworms, can we use some tricky variant of Demon Summoning as activated ability? it destroys corpse, but instead of summoning Demons would give bonus to self?

**Comment by DjWarmonger** [comment]
> No way can realize airship now.

Actually VCMI supports "flying boats" since 1.3.0 at least, but I don't know of any tests or actual implementations of this feature.

**Comment by by003** [comment]
> Actually VCMI supports "flying boats" since 1.3.0 at least, but I don't know of any tests or actual implementations of this feature.

Happy to hear that. It might be realized soon.

I can do any graphical works, even if some def files cannot be opened with regular method, I still can fix them.
![image](https://github.com/vcmi-mods/horn-of-the-abyss/assets/127420617/8a27825a-b097-4e27-9eac-7205d6c6dc5f)
![image](https://github.com/vcmi-mods/horn-of-the-abyss/assets/127420617/2ab77c38-5dc5-4bfc-bf32-1833661cabd2)

Thus no worry about ANY graphs in HotA 1.7. However, I still need some bonuses which can be realized in VCMI.

1. **Ranged first strike** is needed. Nevertheless the new bonus or a subtype of first strike.
2. **Detonation** is needed, I designed it as a damage spell after death, with range 0-1, the damage can be set as a subtype, multipy the quantity of creature who is killed to eliminate.
3. If you have some method for devouring corpse, that's ok.
4. Bonus **Caster without pass current turn**  is needed, like the enchanter, but it is not a passive trigger.

**Comment by by003** [comment]
I can create the demo soon for factory town, with uncomleted creature ability and some building bonuses.

**Comment by by003** [comment]
In progress!
All graphical works are finished, even some files cannot be opened by defpreviwer.
Heroes portraits:
![image](https://github.com/vcmi-mods/horn-of-the-abyss/assets/127420617/1bae4e21-fbb0-447d-b494-7cf7a2b1ec74)
![image](https://github.com/vcmi-mods/horn-of-the-abyss/assets/127420617/ac3908f1-ec2b-4fb6-8d53-b118529c4186)

Creature portraits:
![image](https://github.com/vcmi-mods/horn-of-the-abyss/assets/127420617/f95bdf7f-91a5-42e0-a75b-6a1d8d7cc242)
Dwelling 2 in town:
![image](https://github.com/vcmi-mods/horn-of-the-abyss/assets/127420617/364be57d-3d53-4aec-8d6a-6830da64a1cd)

Map creatures
![image](https://github.com/vcmi-mods/horn-of-the-abyss/assets/127420617/c5d3e884-4a15-4d46-993c-a88ceefa8930)

**Comment by DjWarmonger** [comment]
Detonation is not a passive ability, it has to be enabled by player. Then it's enabled permanently until unit dies, or until the end of combat. There's special button for this action, but it consumes no turn - just like Coatl's Invulnerability.

Since there are already two abilities using activated action button, we can consider supporting it fully in a more general way.

**Comment by LokiLaufeyjarson1712** [comment]
Need any help, soldier?

**Comment by by003** [comment]
Very soon I will put the demo of factory here, and I will show all the improvement aspects. Such as we cannot recruit couatl and dreadnought at the same time.
![image](https://github.com/vcmi-mods/horn-of-the-abyss/assets/127420617/bc6879f0-af27-4154-bff8-4eb475b9f665)

Town screen is ok. 
![image](https://github.com/vcmi-mods/horn-of-the-abyss/assets/127420617/8ae8b135-90ac-4196-8a49-798e1c0065bb)

**Comment by by003** [comment]
https://drive.google.com/file/d/1kLtj8aTN4R1ow0LxNRUgba409b3YYaon/view?usp=sharing

Demo version is done. But I only finish seven heroes. I hope @misiokles or maybe others can finish the remaining ones.

Now the function is ok, but some abilities for creatures are not working yet,

@DjWarmonger could you finish the development of these abilities? 

If it is finished, just put it into hota mods.

**Comment by misiokles** [comment]
I'm not planning to port Factory in neargearest future, somebody must finish rest of the things.

**Comment by by003** [comment]
I know that, so I didn't put factory to public. Just for testing.

**Comment by DjWarmonger** [comment]
It works! Nice job.
Still has some issues though.

This obstacle is passable:
<img width="180" alt="Passable obstacle" src="https://github.com/vcmi-mods/horn-of-the-abyss/assets/2566990/d61690c9-61e1-4783-b9d8-074ab2f83687">

Halfling has old portrait in town garrison:
<img width="361" alt="Old Halfling Portrait" src="https://github.com/vcmi-mods/horn-of-the-abyss/assets/2566990/1a119c26-9905-4caf-8b40-31d020be4023">

**Comment by by003** [comment]
@DjWarmonger  You need to change this portrait in:
![image](https://github.com/vcmi-mods/horn-of-the-abyss/assets/127420617/a067f045-0272-43aa-bfc8-7dd4c7878b45)

![image](https://github.com/vcmi-mods/horn-of-the-abyss/assets/127420617/b935c6a6-984c-462f-af79-704ece25116a)

**Comment by by003** [comment]
I just put it for testing, it still cannot be released into public.

Maybe after the development of new ability.

**Comment by by003** [comment]
@misiokles Please close this and transfer to pull request for hota 1.7.
