### ISSUE TITLE
GameBalance Submod Error

### ISSUE THREAD

**Issue by yche2990** [vcmi-mods/horn-of-the-abyss#90]
I just installed the updated version with Chinese language update.

However, it appears that the gamebalance submod cannot be loaded. The android VCMI shows a warning that it could not load the gamebalance folder.

Please fix the error.

**Comment by lishaoxia1985** [comment]
That will lead to that you can't deselecting the mod on Android.

**Comment by Worst-vd-plas** [comment]
Had the same problem. Fixed it on my end by correcting the JSON syntax errors in [hota/Mods/gameBalance/mod.json](https://github.com/vcmi-mods/horn-of-the-abyss/blob/vcmi-1.5/hota/Mods/gameBalance/mod.json)

I changed this part:
```
		"translations" : [
			"translation/chinese.json",
		]
	},
}
```
to this:
```
		"translations" : [
			"translation/chinese.json"
		]
	}
}
```
(Removed two commas)
After this the Submod successfully loaded.
